"""
Configuration module for USA POI Data Pipeline
"""

from .schema_mapping import (
    SOURCE_COLUMNS,
    DIRECT_MAPPINGS,
    TARGET_SCHEMA,
    FINAL_OUTPUT_COLUMNS,
    STATUS_MAPPING,
    PARENT_TYPE_MAPPING,
    RESTAURANT_KEYWORDS,
    RESTAURANT_LEVEL2_CATEGORIES,
    QSR_BRAND_KEYWORDS,
    DINING_TYPE_THRESHOLDS,
    CATEGORY_COLUMN_CANDIDATES,
    BRAND_COLUMN_CANDIDATES,
)
